// src/components/ProfileSettings.jsx
import React, { useState } from 'react';

export default function ProfileSettings({ 
  userAddress, 
  smartAccountAddress, 
  onClose 
}) {
  const [copiedEOA, setCopiedEOA] = useState(false);
  const [copiedAA, setCopiedAA] = useState(false);

  const copyToClipboard = (text, type) => {
    navigator.clipboard.writeText(text);
    if (type === 'eoa') {
      setCopiedEOA(true);
      setTimeout(() => setCopiedEOA(false), 2000);
    } else {
      setCopiedAA(true);
      setTimeout(() => setCopiedAA(false), 2000);
    }
  };

  const getExplorerLink = (addr) => {
    return `https://amoy.polygonscan.com/address/${addr}`;
  };

  return (
    <div className="min-h-screen bg-surface flex flex-col justify-between overflow-x-hidden relative animate-reveal">
      {/* Background Ambient Blobs */}
      <div className="fixed -top-12 -left-12 w-80 h-80 bg-secondary/5 rounded-full blur-[100px] pointer-events-none -z-10 animate-pulse" />
      <div className="fixed bottom-[-10%] -right-12 w-[350px] h-[350px] bg-primary/5 rounded-full blur-[90px] pointer-events-none -z-10 animate-pulse" />

      {/* Header */}
      <header className="sticky top-0 left-0 right-0 z-40 bg-surface/50 backdrop-blur-xl border-b border-white/[0.05] px-6 py-4 flex items-center justify-between">
        <button
          onClick={onClose}
          className="w-10 h-10 flex items-center justify-center rounded-full bg-white/5 border border-white/10 hover:bg-white/10 text-on-surface transition-all duration-200 cursor-pointer active:scale-95"
        >
          <span className="material-symbols-outlined text-xl">arrow_back</span>
        </button>

        <h3 className="font-headline font-bold text-on-surface text-base">
          Web3 Identity Details
        </h3>

        <div className="w-10 h-10" /> {/* Spacer */}
      </header>

      {/* Main Settings Panel */}
      <main className="flex-1 page-container mt-6 px-6 space-y-6">
        
        {/* Identity Title Card */}
        <div className="glass-card rounded-2xl p-6 border border-white/[0.05] text-center flex flex-col items-center justify-center space-y-4">
          <div className="w-16 h-16 rounded-full signature-gradient flex items-center justify-center font-headline font-bold text-on-primary-fixed shadow-primary text-xl">
            {smartAccountAddress ? smartAccountAddress.substring(2, 5).toUpperCase() : "AA"}
          </div>
          <div>
            <h4 className="font-headline font-bold text-on-surface text-lg">
              Decentralized Identity
            </h4>
            <p className="font-body text-xs text-on-surface-variant mt-1">
              Your assets and notes are secured on-chain using deterministic Account Abstraction.
            </p>
          </div>
        </div>

        {/* EOA Privy Signer Address Details */}
        <div className="glass-card rounded-xl p-5 border border-white/[0.05] space-y-3">
          <div className="flex items-center gap-1.5">
            <span className="material-symbols-outlined text-primary text-sm">key</span>
            <span className="section-label">EOA Privy Signer</span>
          </div>

          <p className="font-body text-xs text-on-surface-variant leading-relaxed">
            This is your social login embedded signer key generated by Privy. It acts as the owner and signer of your smart account.
          </p>

          <div className="flex items-center gap-3 bg-white/5 rounded-xl px-4 py-3 border border-white/[0.03]">
            <span className="font-mono text-xs text-on-surface truncate flex-1 select-all">
              {userAddress || "0x..."}
            </span>
            <button
              onClick={() => copyToClipboard(userAddress, 'eoa')}
              className="p-2 flex items-center justify-center rounded-lg hover:bg-white/10 text-on-surface-variant hover:text-primary transition-all duration-150 cursor-pointer active:scale-90 border-none"
            >
              <span className="material-symbols-outlined text-sm">
                {copiedEOA ? "check" : "content_copy"}
              </span>
            </button>
          </div>
        </div>

        {/* Smart Account AA Address Details */}
        <div className="glass-card rounded-xl p-5 border border-white/[0.05] space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-1.5">
              <span className="material-symbols-outlined text-secondary text-sm">shield</span>
              <span className="section-label">Deterministic Smart Account</span>
            </div>
            <span className="px-2.5 py-0.5 bg-primary/10 border border-primary/20 text-primary text-[9px] font-bold rounded-full uppercase tracking-wider">
              ERC-4337
            </span>
          </div>

          <p className="font-body text-xs text-on-surface-variant leading-relaxed">
            This is your smart account address where notes are anchored. This remains the exact same across all Google or Email logins.
          </p>

          <div className="flex items-center gap-3 bg-white/5 rounded-xl px-4 py-3 border border-white/[0.03]">
            <span className="font-mono text-xs text-on-surface truncate flex-1 select-all font-semibold">
              {smartAccountAddress || "0x..."}
            </span>
            <button
              onClick={() => copyToClipboard(smartAccountAddress, 'aa')}
              className="p-2 flex items-center justify-center rounded-lg hover:bg-white/10 text-on-surface-variant hover:text-primary transition-all duration-150 cursor-pointer active:scale-90 border-none"
            >
              <span className="material-symbols-outlined text-sm">
                {copiedAA ? "check" : "content_copy"}
              </span>
            </button>
          </div>

          {/* Action Links */}
          <div className="pt-2">
            <a
              href={getExplorerLink(smartAccountAddress)}
              target="_blank"
              rel="noreferrer"
              className="flex items-center justify-center gap-1.5 py-3 w-full rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 font-headline font-bold text-xs text-on-surface transition-all duration-200 cursor-pointer select-none active:scale-[0.98]"
            >
              <span className="material-symbols-outlined text-sm">open_in_new</span>
              <span>View on PolygonScan</span>
            </a>
          </div>
        </div>
      </main>

      {/* Footer Info */}
      <footer className="page-container py-8 text-center mt-auto">
        <p className="font-label text-[10px] text-on-surface-variant/30 tracking-wider">
          ChainNotes v2.0.0 · Polygon Testnet Amoy · Pimlico paymaster
        </p>
      </footer>
    </div>
  );
}
